# Generated by Django 5.0.6 on 2024-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
