# Generated by Django 5.0.6 on 2024-07-01 18:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('author', '0002_alter_author_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.AddField(
            model_name='album',
            name='album_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='author.author'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 2, 0, 58, 35, 886444)),
        ),
    ]
